# -*- coding: utf-8 -*-
"""fake_news_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMoX99wYR83Vrx3MeTjsP76fgGjExTH7
"""

# fake_news_project.py
# Fake News Detection Project (Colab-ready)
# Author: Shankar (Rockii Parhyar)

import os
import pandas as pd
import re

# Paths
ZIP_PATH = "/content/fake_or_real_news_csv_zip.py"

# Folder for models / outputs
OUTPUT_DIR = "./models_output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# -----------------
# Text cleaning function
def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r"http\S+|www\.\S+", " ", text)
    text = re.sub(r"<.*?>", " ", text)
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Main function
def main():
    print("Place your dataset at:", ZIP_PATH)
    print("Then run this script in Colab or locally.")
    print("This script will handle dataset loading, cleaning, training and model saving.")

if __name__ == "__main__":
    main()