# -*- coding: utf-8 -*-
"""text_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMoX99wYR83Vrx3MeTjsP76fgGjExTH7
"""

pandas
numpy
scikit-learn
matplotlib
tensorflow
joblib